### ISSUE TITLE
New checker (c160): ensure file_r1 and file_r2 are populated properly depending on paired end or not

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/seq-tools#3]
For paired end sequencing, both `file_r1` and `file_r2` are required, otherwise, only `file_r1` is required (`file_r2` must not be populated). In case of paired end BAM sequencing file, `file_r1` == `file_r2`.

files in `file_r1` / `file_r2` must be in `files` section of the metadata

**Comment by lindaxiang** [comment]
Addressed by https://github.com/icgc-argo/seq-tools/pull/22
