### ISSUE TITLE
from printable characters in ascii find out which characters break our alignment pipeline if used in RG ID

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/seq-tools#32]
the rest characters will become permissible chars that can appear in `read_group_id_in_bam` field

Here is full list of ascii printable characters: http://facweb.cs.depaul.edu/sjost/it212/documents/ascii-pr.htm

**Comment by lindaxiang** [comment]
I did thorough testing of the all the ascii printable characters listed in  http://facweb.cs.depaul.edu/sjost/it212/documents/ascii-pr.htm
The following characters will break the `alignment` worklfow:

Character | Hex | Decimal
-- | -- | --
" | 22 | 34
$ | 24 | 36
/ | 2f | 47
\ | 5c | 92
` | 60 | 96

**Comment by junjun-zhang** [comment]
good know what exact characters break the workflow. Following good practices, the following characters are not typically used in ID fields, let's exclude them (at least for now):

`!` `"` `#` `$` `%` `&` `(` `)` `*` `,` `/` `;` `<` `=` `>` `?` `@` `[` `\` `]` `^` `{` `|` `}` `~` plus white space ( ) and grave accent (`) 

That leaves the following characters:
`'` `+` `-` `.` `:` `_` `0-9` `a-z` `A-Z`

**Comment by junjun-zhang** [comment]
added `+` to the permissible pattern here: https://github.com/icgc-argo/seq-tools/commit/158d29a7ad5d2a7100c7724702c1497883970540#diff-c3abc8623a1bd5978ef0e83bde4aa3f8R36

**Comment by junjun-zhang** [comment]
close this for now, open a new one if we need to update the pattern
