### ISSUE TITLE
New checker (c230): ensure 'file.info.data_category' is populated with 'Sequencing Reads'

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/seq-tools#43]

**Comment by lindaxiang** [comment]
Is `files/info/data_category` required field for `sequencing_experiment`? @junjun-zhang

**Comment by junjun-zhang** [comment]
not completely firm on this, but if we have it in place, nothing needs to be done when later we do need it.

the other point is that it's very simple to do for anyone who is able to prepare the metadata JSON, just add an extra bit hardcoded section.

**Comment by junjun-zhang** [comment]
one thing we can do is to report missing `file.info.data_category` as `WARNING` not `INVALID`, so submitter has a chance to force ignore it.

**Comment by lindaxiang** [comment]
Addressed by https://github.com/icgc-argo/seq-tools/pull/57
