### ISSUE TITLE
New check: repeated identical reads from different read groups

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/seq-tools#66]
One real data file has this problem: https://dcc.icgc.org/repositories/files/FI803381

**Comment by edsu7** [comment]
Test to adress problem:
[c680_repeated_read_names_per_group_in_bam](https://github.com/icgc-argo/seq-tools/blob/_v2/seq_tools/validation/c680_repeated_read_names_per_group_in_bam.py)

Resources (json + bam):
[Duplicate renames with different read groups](https://github.com/icgc-argo/seq-tools/tree/_v2/tests/submissions/anon_chr1_sameReadName_diffReadGroup)
[Duplicate renames with same read groups](https://github.com/icgc-argo/seq-tools/tree/_v2/tests/submissions/anon_chr1_sameReadName_sameReadGroup)

**Comment by edsu7** [comment]
Completed and merged into main. Closing
