### ISSUE TITLE
New check: for BAM submission, detect whether it's paired end or not and whether it matches what's in the metadata

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/seq-tools#71]
This might be a real world example: https://github.com/icgc-argo/workflow-roadmap/issues/94. metadata indicates it's paired end, but the actual data seems miss one end

**Comment by edsu7** [comment]
Test to adress problem:
[c670_rg_is_paired_in_bam](https://github.com/icgc-argo/seq-tools/blob/_v2/seq_tools/validation/c670_rg_is_paired_in_bam.py)

Resources (json + bam):
[Correct bam](https://github.com/icgc-argo/seq-tools/blob/_v2/tests/submissions/anon_chr1_rnaseq/009bebd8-3cf9-45a8-8546-1a09a8bf91a1_complete.json)
[Bam w/ Incorrect strandedness](https://github.com/icgc-argo/seq-tools/blob/_v2/tests/submissions/anon_chr1_rnaseq/009bebd8-3cf9-45a8-8546-1a09a8bf91a1_noStranded.json)
