### ISSUE TITLE
🐛  Regex check not matching schema in c120_permissible_char_in_rg_id.py

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/seq-tools#78]
## Describe the bug
The regex check in seq-tools is currently different from schema.

[Current Seq-tools regex](https://github.com/icgc-argo/seq-tools/blob/caa42feeb68acf1685aec7ad4a4fb4ea531200da/seq_tools/validation/c120_permissible_char_in_rg_id.py#L52):
`^[a-zA-Z0-9_\.\-]{2,}$`

[Schema regex](https://github.com/icgc-argo/argo-metadata-schemas/blob/75a9cbe269419d0e99df929cdf3500b952697512/schemas/sequencing_alignment.json#L359)
`^[a-zA-Z0-9\\-_:\\.]+$`

Fix is to swap regex to match schema.

**Comment by edsu7** [comment]
Added in [URL check for new regex](https://github.com/icgc-argo/seq-tools/blob/c6302ed7abfd4d8688822d3ccb49ebddcae50695/seq_tools/validation/c120_permissible_char_in_rg_id.py#L48) that includes ":"

**Comment by b-f-chan** [comment]
Move to QA until PR merged, then test before closing

**Comment by edsu7** [comment]
Merged into main. Closing
