### ISSUE TITLE
Add README.md for Validation Checks in the Seq-Tools

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/seq-tools#86]
With the increasing number of validation items being added into `seq-tools`, we should add a README.md to include descriptions for all the validation items:

Maybe under folder: `https://github.com/icgc-argo/seq-tools/tree/main/seq_tools/validation`

**Comment by edsu7** [comment]
PR created: https://github.com/icgc-argo/seq-tools/pull/95

**Comment by lindaxiang** [comment]
Move Reademe to Wiki: https://github.com/icgc-argo/seq-tools/wiki

**Comment by b-f-chan** [comment]
Still in progresss, need to move remaining content to the GitHub Wiki

**Comment by b-f-chan** [comment]
@lindaxiang to review content?

**Comment by edsu7** [comment]
Current iteration looks good. Closing.
